train_dataset:
  name: dataset.data_val.PolypObjDataset
  params:
    image_root: '/home/chenzeyu/pycharmprojects/CamoDiffusion/dataset/v3/TrainDataset/Imgs/'
    gt_root: '/home/chenzeyu/pycharmprojects/CamoDiffusion/dataset/v3/TrainDataset/GT/'
    trainsize: 352

test_dataset:
  CASIAv1:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/home/chenzeyu/pycharmprojects/CamoDiffusion/dataset/v3/TestDataset/CASIAv1/Imgs/'
      gt_root: '/home/chenzeyu/pycharmprojects/CamoDiffusion/dataset/v3/TestDataset/CASIAv1/GT/'
      testsize: 352
  Columbia:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/home/chenzeyu/pycharmprojects/CamoDiffusion/dataset/v3/TestDataset/Columbia/Imgs/'
      gt_root: '/home/chenzeyu/pycharmprojects/CamoDiffusion/dataset/v3/TestDataset/Columbia/GT/'
      testsize: 352
  Coverage:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/home/chenzeyu/pycharmprojects/CamoDiffusion/dataset/CASIAv2/TestDataset/Coverage/Imgs/'
      gt_root: '/home/chenzeyu/pycharmprojects/CamoDiffusion/dataset/CASIAv2/TestDataset/Coverage/GT/'
      testsize: 352
  IMD20:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/home/chenzeyu/pycharmprojects/CamoDiffusion/dataset/v3/TestDataset/IMD20/Imgs/'
      gt_root: '/home/chenzeyu/pycharmprojects/CamoDiffusion/dataset/v3/TestDataset/IMD20/GT/'
      testsize: 352
  NIST16:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/home/chenzeyu/pycharmprojects/CamoDiffusion/dataset/CASIAv2/TestDataset/NIST16/Imgs/'
      gt_root: '/home/chenzeyu/pycharmprojects/CamoDiffusion/dataset/CASIAv2/TestDataset/NIST16/GT/'
      testsize: 352